services:
  - type: web
    name: jn-palabras-backend
    env: node
    rootDir: backend
    region: frankfurt # Servidor en Europa (Frankfurt, Alemania) - Cumplimiento GDPR
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.qzdqycvkopijggzeiswl:ZpvpR29gqIeipDtH@aws-0-us-west-2.pooler.supabase.com:5432/postgres

  - type: static
    name: jn-palabras-frontend
    rootDir: frontend
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://jn-palabras-backend.onrender.com

