services:
  - type: web
    name: jn-palabras-backend
    env: node
    region: frankfurt # Servidor en Europa (Frankfurt, Alemania) - Cumplimiento GDPR
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.qzdqycvkopijggzeiswl:ZpvpR29gqIeipDtH@aws-0-us-west-2.pooler.supabase.com:5432/postgres
